# Generated by Django 3.0.7 on 2020-07-25 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('courseid', models.AutoField(primary_key=True, serialize=False)),
                ('stream', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('discription', models.TextField()),
                ('smallImage', models.FileField(upload_to='coursesmall/')),
                ('BigImage', models.FileField(upload_to='coursebig/')),
            ],
        ),
    ]
